    HashMap getWilayaMap()
    {
        HashMap wMap = new HashMap<String,Integer>();
        wMap.put("1. ﻿أدرار",R.array.W01);
        wMap.put("2. الشلف",R.array.W02);
        wMap.put("3. الأغواط",R.array.W03);
        wMap.put("4. أم البواقي",R.array.W04);
        wMap.put("5. باتنة",R.array.W05);
        wMap.put("6. بجاية",R.array.W06);
        wMap.put("7. بسكرة",R.array.W07);
        wMap.put("8. بشار",R.array.W08);
        wMap.put("9. البليدة",R.array.W09);
        wMap.put("10. البويرة",R.array.W10);
        wMap.put("11. تمنراست",R.array.W11);
        wMap.put("12. تبسة",R.array.W12);
        wMap.put("13. تلمسان",R.array.W13);
        wMap.put("14. تيارت",R.array.W14);
        wMap.put("15. تيزي وزو",R.array.W15);
        wMap.put("16. الجزائر",R.array.W16);
        wMap.put("17. الجلفة",R.array.W17);
        wMap.put("18. جيجل",R.array.W18);
        wMap.put("19. سطيف",R.array.W19);
        wMap.put("20. سعيدة",R.array.W20);
        wMap.put("21. سكيكدة",R.array.W21);
        wMap.put("22. سيدي بلعباس",R.array.W22);
        wMap.put("23. عنابة",R.array.W23);
        wMap.put("24. قالمة",R.array.W24);
        wMap.put("25. قسنطينة",R.array.W25);
        wMap.put("26. المدية",R.array.W26);
        wMap.put("27. مستغانم",R.array.W27);
        wMap.put("28. المسيلة",R.array.W28);
        wMap.put("29. معسكر",R.array.W29);
        wMap.put("30. ورقلة",R.array.W30);
        wMap.put("31. وهران",R.array.W31);
        wMap.put("32. البيض",R.array.W32);
        wMap.put("33. إليزي",R.array.W33);
        wMap.put("34. برج بوعريريج",R.array.W34);
        wMap.put("35. بومرداس",R.array.W35);
        wMap.put("36. الطارف",R.array.W36);
        wMap.put("37. تندوف",R.array.W37);
        wMap.put("38. تيسمسيلت",R.array.W38);
        wMap.put("39. الوادي",R.array.W39);
        wMap.put("40. خنشلة",R.array.W40);
        wMap.put("41. سوق أهراس",R.array.W41);
        wMap.put("42. تيبازة",R.array.W42);
        wMap.put("43. ميلة",R.array.W43);
        wMap.put("44. عين الدفلى",R.array.W44);
        wMap.put("45. النعامة",R.array.W45);
        wMap.put("46. عين تموشنت",R.array.W46);
        wMap.put("47. غرداية",R.array.W47);
        wMap.put("48. غليزان",R.array.W48);
        return wMap;
    }
